base_url = "https://parallel-time.github.io"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true
theme = "academic-workshop"

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
title = {tagline = "ICML 2026 Workshop on", title = "The Promises and Perils of Parallelizing Sequential Computation", subtitles = [""], url = true}
banner = {extension = "svg", size = "fit-height", fade = true}
buttons = [{name = "Registration", url = "/registration"}, {name="Instructions", url="/instructions"}, {name="Programme", url="programme"}, {name="About", url="/about"}]
header_pages = [{name = "Home", url = "/#home"},{name = "Programme", url = "/#programme"}, {name = "Registration", url = "/registration"}, {name="Instructions", url="/instructions"}]
